version: "3.8"

services:
  dev_backend:
    image: dev_backend:latest
    ports:
      - 3000:3000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first

  dev_frontend:
    image: dev_backend:latest
    ports:
      - 5000:5000
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first

  dev_nginx:
    build: ./nginx
    container_name: dev_nginx_container
    ports:
      - 80:80
      - 443:443
    depends_on:
      - dev_backend
      - dev_frontend