version: "3.8"

services:
  main_backend:
    build: ./backend
    container_name: main_backend_container
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=AKIA4VFKZCU33SOXB4XC
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-northeast-2

  main_frontend:
    build: ./frontend
    container_name: main_frontend_container
    ports:
      - "5000:5000"
