version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    volumes:
      - /hostpath/provisioning:/etc/provisioning
    ports:
      - 9000:3000

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /hostpath/www:/var/www/html
      - /hostpath/certbot/etc:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - /hostpath/certbot/etc:/etc/letsencrypt
      - /hostpath/certbot/var:/var/lib/letsencrypt
      - /hostpath/www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email tjfgkssk9472@gmail.com --agree-tos --no-eff-email --force-renewal -d tairot.online -v
    # depends_on:
    #   - nginx
