version: "3.8"

services:
  dev_backend:
    build: ./backend
    image: dev_backend
    container_name: dev_backend
    ports:
      - 3000:3000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

  dev_frontend:
    build: ./frontend
    image: dev_frontend
    container_name: dev_frontend
    ports:
      - 5000:5000

  dev_nginx:
    build: ./nginx
    image: dev_nginx
    container_name: dev_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /hostpath/www:/var/www/html
      - /hostpath/certbot/etc:/etc/letsencrypt:ro
    depends_on:
      - dev_backend
      - dev_frontend