version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "3001:3000"
    environment:
    # volumes:
    #   - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
