version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "3001:3000"
    environment:
      - AWS_ACCESS_KEY_ID=AKIA4VFKZCU3VLHZKPVJ

      - AWS_SECRET_ACCESS_KEY=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

      - AWS_REGION=ap-northeast-2
    # volumes:
    #   - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
