version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    # volumes:
    #   - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  nginx:
    # image: nginx:latest
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/data:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command: certonly --webroot -w /var/www/certbot --email tjfgkssk9472@gmail.com --agree-tos --no-eff-email -d tairot.online
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/logs:/var/log/letsencrypt:rw
      - ./certbot/data:/var/www/certbot:rw
