version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      -"./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      -9090:9090

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    # volumes:
    #   - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
