ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
# FROM docker.elastic.co/kibana/kibana:7.17.11

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
