global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['dev_prometheus:9090']
  - job_name: node
    static_configs:
      - targets: ['dev_node-exporter:9100']