ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
# FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.11

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
