ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
# FROM docker.elastic.co/logstash/logstash:7.17.11

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
